#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#  @generated
#
cdef class SQLSchema_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.SQLSchema

    def __iter__(self):
        yield "columnNames", self.columnNames
        yield "columnTypes", self.columnTypes
        yield "tableNames", self.tableNames
        yield "columnToTable", self.columnToTable
        yield "tableToColumns", self.tableToColumns
        yield "foreignKeys", self.foreignKeys
        yield "primaryKeys", self.primaryKeys

cdef class RegisterSQLSchemaException_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.RegisterSQLSchemaException

    def __iter__(self):
        yield "dbId", self.dbId
        yield "message", self.message

cdef class RegisterTokenizerException_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.RegisterTokenizerException

    def __iter__(self):
        yield "message", self.message

cdef class TokenizerNotRegisteredException_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.TokenizerNotRegisteredException

    def __iter__(self):
        yield "message", self.message

cdef class TokenizerPrefixException_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.TokenizerPrefixException

    def __iter__(self):
        yield "message", self.message

cdef class ModeException_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.ModeException

    def __iter__(self):
        yield "message", self.message

cdef class FeedFatalException_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.FeedFatalException

    def __iter__(self):
        yield "tokenizerNotRegisteredException", self.tokenizerNotRegisteredException
        yield "tokenizerPrefixException", self.tokenizerPrefixException
        yield "modeException", self.modeException

cdef class FeedException_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.FeedException

    def __iter__(self):
        yield "feedFatalException", self.feedFatalException

cdef class FeedParseFailure_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.FeedParseFailure

    def __iter__(self):
        yield "input", self.input
        yield "contexts", self.contexts
        yield "description", self.description

cdef class FeedTimeoutFailure_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.FeedTimeoutFailure

    def __iter__(self):
        yield "message", self.message

cdef class FeedPartialSuccess_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.FeedPartialSuccess

    def __iter__(self):
        pass

cdef class FeedCompleteSuccess_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.FeedCompleteSuccess

    def __iter__(self):
        yield "leftover", self.leftover

cdef class FeedResult_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.FeedResult

    def __iter__(self):
        yield "feedParseFailure", self.feedParseFailure
        yield "feedTimeoutFailure", self.feedTimeoutFailure
        yield "feedPartialSuccess", self.feedPartialSuccess
        yield "feedCompleteSuccess", self.feedCompleteSuccess

cdef class BatchFeedResult_Builder(thrift.py3.builder.StructBuilder):
    _struct_type = _picard_types.BatchFeedResult

    def __iter__(self):
        yield "batchId", self.batchId
        yield "topToken", self.topToken
        yield "feedResult", self.feedResult

